apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metadata-app
  template:
    metadata:
      labels:
        app: metadata-app
    spec:
      containers:
        - name: metadata-container
          image: shayan1337/metadata-service:v1
          ports:
            - containerPort: 8080