apiVersion: v1
kind: Pod
metadata:
  name: metadata-service-pod
  labels:
    app: metadata-app
spec:
  containers:
    - image: shayan1337/metadata-service:v1
      name: metadata-service-container
      ports:
        - containerPort: 8080
          protocol: TCP
